#!/usr/bin/env bash
echo HOY COMO ESTAS
edad=28
echo CREO QUE TIENES $edad ANIOS
echo -e "ESTA \nFRASE \nSE \nMOSTRARA \nPALABRA \nEN \nUNA \nLINEA \nDISTINTA \nCADA \nPALABRA"
echo -e "SUPRIMIR LO QUE VIENE A CONTINUACION \cel SALTO DE LINEA"
echo IMPRIMIR TODOS LOS FICHEROS Y CARPETAS A MODO COMANDO ls
echo *
echo IMPRIMIR TODOS LOS FICHEROS DE UN FORMATO CONCRETO
echo *.sh
echo "ESTA FRASE SE DIRECCIONA A UN ARCHIVO DONDE QUEDA GRABADO" > salvar.txt
echo "ESTO QUE SIGUE SE ANIADE AL ARCHIVO" >> salvar.txt
echo -n "OMITIMOS EL SALTO DE LINEA"
read -rsp $'\nPress enter to continue....'